{
  "schemaVersion": 3,
  "profile": "custom",
  "adsEnabled": true,
  "bannerEnabled": true,
  "interstitialEnabled": true,
  "rewardedEnabled": true,
  "nativeEnabled": true,
  "appOpenEnabled": true,
  "useTestAds": true,
  "bannerId": "R-M-19077132-1",
  "interstitialId": "R-M-19077132-3",
  "rewardedId": "R-M-19077132-4",
  "nativeId": "R-M-19077132-2",
  "appOpenId": "R-M-19077132-5",
  "interstitialIntervalMs": 20000,
  "interstitialMaxSession": 30,
  "interstitialColdStartMs": 20000,
  "weaponDetailTriggerCount": 1,
  "caseOpenTriggerCount": 1,
  "missionClaimTriggerCount": 1,
  "navigationTriggerCount": 1,
  "appOpenMinBackgroundMs": 30000,
  "appOpenIntervalMs": 60000,
  "appOpenMaxSession": 6,
  "fullscreenCooldownMs": 15000,
  "nativeIntervalWeapons": 2,
  "nativeIntervalGuides": 2,
  "nativeIntervalKnives": 2,
  "nativeIntervalSkins": 2,
  "bannerStickyEnabled": true,
  "configRefreshMs": 60000,
  "retryBaseDelayMs": 15000,
  "retryMaxAttempts": 3,
  "bannerRetryDelayMs": 30000,
  "nativeRetryDelayMs": 30000,
  "enabledTriggers": [
    "WEAPON_DETAIL_OPEN",
    "WEAPON_DETAIL_EXIT",
    "GUIDE_DETAIL_EXIT",
    "TRAINING_COMPLETE",
    "CASE_OPEN_COMPLETE",
    "MISSION_CLAIM",
    "KNIFE_DETAIL_EXIT",
    "NAVIGATION",
    "ONBOARDING_COMPLETE",
    "SCREEN_EXIT"
  ],
  "disabledPlacements": [],
  "stickyBannerRoutes": [
    "home",
    "weapons",
    "skins",
    "knife_list",
    "weapon",
    "knife_detail",
    "inventory",
    "guides",
    "wallet",
    "profile",
    "settings",
    "calculator",
    "games",
    "lab",
    "quiz"
  ],
  "nativeFooterRoutes": [
    "weapon",
    "knife_detail",
    "settings"
  ],
  "interstitialExcludedRoutes": [
    "onboarding",
    "games",
    "quiz"
  ],
  "configVersion": 1,
  "appOpenColdStartEnabled": true,
  "appOpenResumeEnabled": true,
  "onboardingInterstitialEnabled": true,
  "entryAdWaitMs": 4000,
  "rewardedGoldAmount": 100,
  "nativeRoutes": []
}
